// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK_PVKqlFuPVt3Rx6DEgZZa1o-Mzra53Q',
    appId: '1:598136815123:web:9292584a10d5ed58fc09e6',
    messagingSenderId: '598136815123',
    projectId: 'ebycheon-tiktok-clone',
    authDomain: 'ebycheon-tiktok-clone.firebaseapp.com',
    storageBucket: 'ebycheon-tiktok-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-BLQednaNsPjN-3r1dEDSMk9a_svt65g',
    appId: '1:598136815123:android:64f70b4b71732a27fc09e6',
    messagingSenderId: '598136815123',
    projectId: 'ebycheon-tiktok-clone',
    storageBucket: 'ebycheon-tiktok-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvZSICUHMPDOqRqMpvU0W4QmFgwQJpIpk',
    appId: '1:598136815123:ios:a6febeaa340dd3e3fc09e6',
    messagingSenderId: '598136815123',
    projectId: 'ebycheon-tiktok-clone',
    storageBucket: 'ebycheon-tiktok-clone.appspot.com',
    iosClientId: '598136815123-ltjn7s4frvc2on2o59louar423hq7b94.apps.googleusercontent.com',
    iosBundleId: 'com.ebycheon.tiktokclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvZSICUHMPDOqRqMpvU0W4QmFgwQJpIpk',
    appId: '1:598136815123:ios:ab732969827504f7fc09e6',
    messagingSenderId: '598136815123',
    projectId: 'ebycheon-tiktok-clone',
    storageBucket: 'ebycheon-tiktok-clone.appspot.com',
    iosClientId: '598136815123-m1movp1828uoohn99vp2ddujg0tjgnit.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
